/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package train.tricaet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;

public class Project extends javax.swing.JFrame {

    /**
     * Creates new form Project
     */
    public Project() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TrainTicket = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SunTotal = new javax.swing.JLabel();
        Tax = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Totalbuttn = new javax.swing.JButton();
        Resent = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Subtext = new javax.swing.JTextField();
        Taxtext = new javax.swing.JTextField();
        Totaltext = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Classte = new javax.swing.JLabel();
        Tickettype1 = new javax.swing.JLabel();
        Adult1 = new javax.swing.JLabel();
        Chaild1 = new javax.swing.JLabel();
        Cltext = new javax.swing.JTextField();
        tricketT1 = new javax.swing.JTextField();
        Adtext = new javax.swing.JTextField();
        Chtext = new javax.swing.JTextField();
        From = new javax.swing.JLabel();
        To = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        Fromtext = new javax.swing.JTextField();
        Totext = new javax.swing.JTextField();
        Datetext = new javax.swing.JTextField();
        Timetext = new javax.swing.JTextField();
        TicketNo = new javax.swing.JLabel();
        TNoText = new javax.swing.JTextField();
        Price = new javax.swing.JLabel();
        Pricetext = new javax.swing.JTextField();
        Rount = new javax.swing.JLabel();
        Rounttext = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Standrad = new javax.swing.JRadioButton();
        Economy = new javax.swing.JRadioButton();
        FirstC = new javax.swing.JRadioButton();
        Class = new javax.swing.JLabel();
        Trickettype = new javax.swing.JLabel();
        Single = new javax.swing.JRadioButton();
        Return = new javax.swing.JRadioButton();
        Adult = new javax.swing.JLabel();
        Child = new javax.swing.JLabel();
        Ayes = new javax.swing.JRadioButton();
        Cyes = new javax.swing.JRadioButton();
        Destination = new javax.swing.JLabel();
        Choose = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(2000, 1800));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        TrainTicket.setBackground(new java.awt.Color(255, 255, 255));
        TrainTicket.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TrainTicket.setText("Train Tricket Management System");

        jLabel1.setFont(new java.awt.Font("Webdings", 0, 96)); // NOI18N
        jLabel1.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(TrainTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(TrainTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        SunTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SunTotal.setForeground(new java.awt.Color(255, 153, 0));
        SunTotal.setText("Subtotal");

        Tax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Tax.setForeground(new java.awt.Color(204, 0, 204));
        Tax.setText("Tax");

        Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 51, 51));
        Total.setText("Total");

        Totalbuttn.setBackground(new java.awt.Color(0, 0, 0));
        Totalbuttn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Totalbuttn.setForeground(new java.awt.Color(51, 255, 51));
        Totalbuttn.setText("Total");
        Totalbuttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalbuttnMouseClicked(evt);
            }
        });
        Totalbuttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalbuttnActionPerformed(evt);
            }
        });

        Resent.setBackground(new java.awt.Color(0, 204, 204));
        Resent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Resent.setForeground(new java.awt.Color(0, 0, 255));
        Resent.setText("Resent");
        Resent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResentActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(0, 0, 0));
        Exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 0));
        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Subtext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Taxtext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Totaltext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SunTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Taxtext)
                    .addComponent(Totaltext)
                    .addComponent(Subtext, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Totalbuttn)
                .addGap(71, 71, 71)
                .addComponent(Resent)
                .addGap(67, 67, 67)
                .addComponent(Exit)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SunTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Subtext, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Taxtext, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Totaltext, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Resent)
                    .addComponent(Exit)
                    .addComponent(Totalbuttn))
                .addGap(24, 24, 24))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        Classte.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Classte.setForeground(new java.awt.Color(102, 255, 102));
        Classte.setText("Class");

        Tickettype1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Tickettype1.setForeground(new java.awt.Color(51, 51, 255));
        Tickettype1.setText("Tricket Type");

        Adult1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Adult1.setForeground(new java.awt.Color(0, 153, 153));
        Adult1.setText("Adult");

        Chaild1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Chaild1.setForeground(new java.awt.Color(255, 51, 51));
        Chaild1.setText("Child");

        Cltext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tricketT1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Adtext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Chtext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        From.setBackground(new java.awt.Color(102, 255, 102));
        From.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        From.setForeground(new java.awt.Color(0, 0, 255));
        From.setText("From");

        To.setBackground(new java.awt.Color(153, 255, 153));
        To.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        To.setForeground(new java.awt.Color(204, 0, 204));
        To.setText("To");

        Date.setBackground(new java.awt.Color(255, 255, 51));
        Date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Date.setForeground(new java.awt.Color(204, 0, 51));
        Date.setText("Date");

        Time.setBackground(new java.awt.Color(102, 255, 102));
        Time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Time.setForeground(new java.awt.Color(204, 0, 204));
        Time.setText("Time");

        TicketNo.setBackground(new java.awt.Color(255, 153, 153));
        TicketNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TicketNo.setForeground(new java.awt.Color(255, 255, 51));
        TicketNo.setText("Ticket No.");

        Price.setBackground(new java.awt.Color(102, 255, 0));
        Price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Price.setForeground(new java.awt.Color(0, 153, 153));
        Price.setText("Price");

        Rount.setBackground(new java.awt.Color(51, 51, 255));
        Rount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Rount.setForeground(new java.awt.Color(102, 51, 255));
        Rount.setText("Round");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Classte, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cltext, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Tickettype1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(Adult1)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tricketT1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Adtext)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Chaild1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(Chtext)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(To, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                                    .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Totext)
                                    .addComponent(Datetext)
                                    .addComponent(Timetext, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(From, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Fromtext, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Pricetext, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(TNoText)
                            .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rount, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TicketNo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rounttext))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Classte, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tickettype1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adult1)
                    .addComponent(Chaild1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tricketT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Chtext, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Adtext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Cltext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(TicketNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(From, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(Fromtext)
                    .addComponent(TNoText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Price)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pricetext, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rount)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Totext, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Datetext, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Timetext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Rounttext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        Standrad.setBackground(new java.awt.Color(255, 255, 51));
        Standrad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Standrad.setText("Standrad");

        Economy.setBackground(new java.awt.Color(255, 0, 0));
        Economy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Economy.setText("Economy");

        FirstC.setBackground(new java.awt.Color(51, 255, 51));
        FirstC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FirstC.setForeground(new java.awt.Color(0, 0, 204));
        FirstC.setText("First Class");

        Class.setBackground(new java.awt.Color(51, 255, 255));
        Class.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Class.setForeground(new java.awt.Color(255, 153, 51));
        Class.setText("Class");

        Trickettype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Trickettype.setForeground(new java.awt.Color(102, 102, 255));
        Trickettype.setText("Tricket Type");

        Single.setBackground(new java.awt.Color(102, 0, 102));
        Single.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Single.setForeground(new java.awt.Color(51, 51, 255));
        Single.setText("Single");

        Return.setBackground(new java.awt.Color(255, 204, 51));
        Return.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Return.setForeground(new java.awt.Color(0, 153, 153));
        Return.setText("Return");

        Adult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Adult.setForeground(new java.awt.Color(255, 153, 204));
        Adult.setText("Adult");

        Child.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Child.setForeground(new java.awt.Color(0, 102, 102));
        Child.setText("Child");

        Ayes.setBackground(new java.awt.Color(0, 204, 204));
        Ayes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Ayes.setForeground(new java.awt.Color(255, 0, 51));
        Ayes.setText("Yes");

        Cyes.setBackground(new java.awt.Color(255, 255, 204));
        Cyes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Cyes.setForeground(new java.awt.Color(153, 0, 153));
        Cyes.setText("Yes");

        Destination.setBackground(new java.awt.Color(0, 204, 0));
        Destination.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Destination.setForeground(new java.awt.Color(255, 0, 102));
        Destination.setText("Destation");

        Choose.setBackground(new java.awt.Color(255, 255, 51));
        Choose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Choose.setForeground(new java.awt.Color(102, 102, 0));
        Choose.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mymensingh", "Dhakha", "Jamalpur", "Haluaghat" }));
        Choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Economy)
                    .addComponent(FirstC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Standrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Class, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Single)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ayes))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(Trickettype)
                                .addGap(52, 52, 52)
                                .addComponent(Adult, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Child, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cyes, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Return)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Destination, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addComponent(Choose, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Class, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Trickettype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Adult, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Child, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Standrad)
                    .addComponent(Single)
                    .addComponent(Ayes)
                    .addComponent(Cyes))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Destination, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Economy)
                        .addComponent(Return)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstC)
                    .addComponent(Choose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void ResentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResentActionPerformed
        // TODO add your handling code here:
        Subtext.setText(null);
        Taxtext.setText(null);
        Totaltext.setText(null);
        Cltext.setText(null);
        tricketT1.setText(null);
        Adtext.setText(null);
       Chtext.setText(null);
       TNoText.setText(null);
       Pricetext.setText(null);
       Rounttext.setText(null);
       Fromtext.setText(null);
       Totext.setText(null);
       Timetext.setText(null);
       Datetext.setText(null);
       
               
       
        
    }//GEN-LAST:event_ResentActionPerformed

    private void TotalbuttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalbuttnActionPerformed
        
     ////// date and time ////////////    
     Calendar timer = Calendar.getInstance();
     timer.getTime();
     SimpleDateFormat tTime = new SimpleDateFormat("HH :mm : ss");
       Timetext.setText( tTime.format(timer.getTime()));
    
     SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-yyy");
       Datetext.setText(Tdate.format(timer.getTime()));
     
    
     
     ///// avobe the finish date and time /////////
     Fromtext.setText("Komlapur");
     Totext.setText((String) Choose.getSelectedItem()+" * ");
     int num1;
     String sq = "";
     num1 = 1325 + (int)( Math.random()*4238);
     sq += num1+1325;
      TNoText.setText(sq);
      Rounttext.setText("Any");
      
     
     
     
     
     
     
    }//GEN-LAST:event_TotalbuttnActionPerformed

    private void TotalbuttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalbuttnMouseClicked
        // TODO add your handling code here:
        double tax = 19.50;
        double Milesk8 = 25.78;
        double Milesk12= 25.10;
        double Milesk20 = 45.23;
        double Milesk30 = 55.98;
        double totalcost, eco = 3.85, fclass =5.60;
        ///one way///////
        if ((Standrad .isSelected()) && ( Single.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Mymensingh")){
            
            totalcost = (tax * Milesk8)/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk8);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", Milesk8+totalcost);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("NOE way");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///one 2 way ///////
        else if ((Standrad .isSelected()) && ( Return.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Mymensingh")){
            
            totalcost = (tax * Milesk8)/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk8*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk8+totalcost)*2);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("RETURN");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        /// 3 way/////
         else if ((Standrad .isSelected()) && ( Single.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Mymensingh")){
            
            totalcost = (tax * Milesk8)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk8);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk8+totalcost)-5.19);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("ONE WAY");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
         ///// 4 way/////
        else if ((Standrad .isSelected()) && ( Return.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Mymensingh")){
            
            totalcost = (tax *( Milesk8*2) /100);
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (Milesk8*2));
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk8+totalcost) *2)-28.05);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("RETURN");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
        ////1 ////
        else if ((Standrad .isSelected()) && ( Single.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Dhakha")){
            
            totalcost = (tax * Milesk12)/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk12);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", Milesk12+totalcost);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("NOE way");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///// 2////
        else if ((Standrad .isSelected()) && ( Return.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Dhakha")){
            
            totalcost = (tax * Milesk12)/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk12*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk12+totalcost)*2);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("RETURN");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///3 /////
        else if ((Standrad .isSelected()) && ( Single.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Dhakha")){
            
            totalcost = (tax * Milesk8)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk8);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk8+totalcost)-5.19);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
            tricketT1.setText("One way");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
        /// 4/////
        else if ((Standrad .isSelected()) && ( Return.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Dhakha")){
            
            totalcost = (tax *( Milesk12)*2)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk12*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk12+totalcost)*2)-28.05);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("RETURN");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
        /// 1////
        
        if ((Standrad .isSelected()) && ( Single.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Jamalpur")){
            
            totalcost = (tax * Milesk20)/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk20);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", Milesk20+totalcost);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("NOE way");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///one 2 way ///////
        else if ((Standrad .isSelected()) && ( Return.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Jamalpur")){
            
            totalcost = (tax * Milesk20)/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk20*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk20+totalcost)*2);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("RETURN");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        /// 3 way/////
         else if ((Standrad .isSelected()) && ( Single.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Jamalpur")){
            
            totalcost = (tax * Milesk20)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk20);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk20+totalcost)-5.19);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("ONE WAY");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
         ///// 4 way/////
        else if ((Standrad .isSelected()) && ( Return.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Jamalpur")){
            
            totalcost = (tax *( Milesk20)*2)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk20*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk20+totalcost)*2)-28.05);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("RETURN");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
        
        
         /// 1////
        
        if ((Standrad .isSelected()) && ( Single.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Haluaghat")){
            
            totalcost = (tax * Milesk30)/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk30);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", Milesk30+totalcost);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("NOE way");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///one 2 way ///////
        else if ((Standrad .isSelected()) && ( Return.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Haluaghat")){
            
            totalcost = (tax * Milesk30)/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk30*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk30+totalcost)*2);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("RETURN");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        /// 3 way/////
         else if ((Standrad .isSelected()) && ( Single.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Haluaghat")){
            
            totalcost = (tax * Milesk30)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk30);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk30+totalcost)-5.19);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("ONE WAY");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
         ///// 4 way/////
        else if ((Standrad .isSelected()) && ( Return.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Haluaghat")){
            
            totalcost = (tax *( Milesk30)*2)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk30*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk30+totalcost)*2)-28.05);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("STD");
             tricketT1.setText("RETURN");
             Adtext.setText("Nill");
             Chtext.setText("one");
        }
            ////////////eco///////////////////////////////////////////////////////
            /////1///////
        
        else if ((Economy .isSelected()) && ( Single.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Mymensingh")){
            
            totalcost = (tax *(Milesk8+eco))/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk8+eco);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", Milesk8+totalcost+eco);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("NOE way");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///2//////
         else if ((Economy .isSelected()) && ( Return.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Mymensingh")){
            
            totalcost = (tax *((Milesk8+eco)*2))/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", ((Milesk8+eco)*2));
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk8+totalcost+eco)*2));
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("RETURN");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///3/////
        else if ((Economy .isSelected()) && ( Single.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Mymensingh")){
            
            totalcost = (tax * Milesk8+eco)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk30+eco);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (eco+Milesk30+totalcost)-5.19);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("ONE WAY");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
         ///// 4 way/////
        else if ((Standrad .isSelected()) && ( Return.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Mymensingh")){
            
            totalcost = (tax *( Milesk8+eco)*2)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (eco+Milesk30)*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk30+eco+totalcost)*2)-28.05);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("RETURN");
             Adtext.setText("Nill");
             Chtext.setText("one");
        }
        /////////eco Dhakha///////////
         else if ((Economy .isSelected()) && ( Single.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Dhakha")){
            
            totalcost = (tax *(Milesk12+eco))/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk12+eco);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", Milesk12+totalcost+eco);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("NOE way");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///2//////
         else if ((Economy .isSelected()) && ( Return.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Dhakha")){
            
            totalcost = (tax *((Milesk12+eco)*2))/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", ((Milesk12+eco)*2));
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk12+totalcost+eco)*2));
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("RETURN");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///3/////
        else if ((Economy .isSelected()) && ( Single.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Dhakha")){
            
            totalcost = (tax * Milesk12+eco)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk12+eco);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (eco+Milesk12+totalcost)-5.19);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("ONE WAY");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
         ///// 4 way/////
        else if ((Economy .isSelected()) && ( Return.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Dhakha")){
            
            totalcost = (tax *( Milesk12+eco)*2)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (eco+Milesk12)*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk12+eco+totalcost)*2)-28.05);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("RETURN");
             Adtext.setText("Nill");
             Chtext.setText("one");
        }
        /////Jamalpur/////
        else if ((Economy .isSelected()) && ( Single.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Jamalpur")){
            
            totalcost = (tax *(Milesk20+eco))/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk20+eco);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", Milesk20+totalcost+eco);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("NOE way");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///2//////
         else if ((Economy .isSelected()) && ( Return.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Jamalpur")){
            
            totalcost = (tax *((Milesk20+eco)*2))/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", ((Milesk20+eco)*2));
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk20+totalcost+eco)*2));
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("RETURN");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///3/////
        else if ((Economy .isSelected()) && ( Single.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Jamalpur")){
            
            totalcost = (tax * Milesk20+eco)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk20+eco);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (eco+Milesk20+totalcost)-5.19);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("ONE WAY");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
         ///// 4 way/////
        else if ((Economy .isSelected()) && ( Return.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Jamalpur")){
            
            totalcost = (tax *( Milesk20+eco)*2)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (eco+Milesk20)*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk20+eco+totalcost)*2)-28.05);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("RETURN");
             Adtext.setText("Nill");
             Chtext.setText("one");
        }
        //////Haluaghat//////
        else if ((Economy .isSelected()) && ( Single.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Haluaghat")){
            
            totalcost = (tax *(Milesk30+eco))/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk30+eco);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", Milesk30+totalcost+eco);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("NOE way");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///2//////
         else if ((Economy .isSelected()) && ( Return.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Haluaghat")){
            
            totalcost = (tax *((Milesk30+eco)*2))/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", ((Milesk30+eco)*2));
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk30+totalcost+eco)*2));
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("RETURN");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        ///3/////
        else if ((Economy .isSelected()) && ( Single.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Haluaghat")){
            
            totalcost = (tax * Milesk30+eco)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk30+eco);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (eco+Milesk30+totalcost)-5.19);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("ONE WAY");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
         ///// 4 way/////
        else if ((Economy .isSelected()) && ( Return.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Haluaghat")){
            
            totalcost = (tax *( Milesk30+eco)*2)/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (eco+Milesk30)*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk30+eco+totalcost)*2)-28.05);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Economy");
             tricketT1.setText("RETURN");
             Adtext.setText("Nill");
             Chtext.setText("one");
        }
         ///one way///////
        if ((FirstC .isSelected()) && ( Single.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Mymensingh")){
            
            totalcost = (tax * (Milesk8+fclass))/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk8+fclass);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f",fclass+ Milesk8+totalcost);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Firstclass");
             tricketT1.setText("NOE way");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
            
        }
        ///one 2 way ///////
        else if ((FirstC .isSelected()) && ( Return.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Mymensingh")){
            
            totalcost = (tax * (fclass+Milesk8)*2)/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (fclass+Milesk8)*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk8+fclass+totalcost)*2);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("FirstClass");
             tricketT1.setText("RETURN");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        /// 3 way/////
         else if ((FirstC.isSelected()) && ( Single.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Mymensingh")){
            
            totalcost = (tax * (fclass+Milesk8))/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (fclass+Milesk8));
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk8+fclass+totalcost)-5.19);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("FirstClass");
             tricketT1.setText("ONE WAY");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
         ///// 4 way/////
        else if ((FirstC .isSelected()) && ( Return.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Mymensingh")){
            
            totalcost = (tax *( Milesk8+fclass)*2) /100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (Milesk8+fclass)*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk8+fclass+totalcost) *2)-28.05);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("FirstClass");
             tricketT1.setText("RETURN");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
         ///one way///////
        if ((FirstC .isSelected()) && ( Single.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Dhakha")){
            
            totalcost = (tax * (Milesk12+fclass))/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk12+fclass);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f",fclass+ Milesk12+totalcost);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Firstclass");
             tricketT1.setText("NOE way");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
            
        }
        ///one 2 way ///////
        else if ((FirstC .isSelected()) && ( Return.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Dhakha")){
            
            totalcost = (tax * (fclass+Milesk12)*2)/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (fclass+Milesk12)*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk12+fclass+totalcost)*2);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("FirstClass");
             tricketT1.setText("RETURN");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
        /// 3 way/////
         else if ((FirstC.isSelected()) && ( Single.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Dhakha")){
            
            totalcost = (tax * (fclass+Milesk8))/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (fclass+Milesk8));
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk8+fclass+totalcost)-5.19);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("FirstClass");
             tricketT1.setText("ONE WAY");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
         ///// 4 way/////
        else if ((FirstC .isSelected()) && ( Return.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Dhakha")){
            
            totalcost = (tax *( Milesk12+fclass)*2) /100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (Milesk12+fclass)*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk12+fclass+totalcost) *2)-28.05);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("FirstClass");
             tricketT1.setText("RETURN");
             Adtext.setText("Nill");
             Chtext.setText("one");
    }//GEN-LAST:event_TotalbuttnMouseClicked

    private void ChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChooseActionPerformed
     ///one way///////
        if ((FirstC .isSelected()) && ( Single.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Jamalpur")){
            
            totalcost = (tax * (Milesk20+fclass))/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk20+fclass);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f",fclass+ Milesk20+totalcost);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Firstclass");
             tricketT1.setText("NOE way");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
            
        }
}
        ///one 2 way ///////
        else if ((FirstC .isSelected()) && ( Return.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Jamalpur")){
            
            totalcost = (tax * (fclass+Milesk20)*2)/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (fclass+Milesk20)*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk20+fclass+totalcost)*2);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("FirstClass");
             tricketT1.setText("RETURN");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
        }
}
        /// 3 way/////
         else if ((FirstC.isSelected()) && ( Single.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Jamalpur")){
            
            totalcost = (tax * (fclass+Milesk20))/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (fclass+Milesk20));
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk20+fclass+totalcost)-5.19);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("FirstClass");
             tricketT1.setText("ONE WAY");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
         ///// 4 way/////
        else if ((FirstC .isSelected()) && ( Return.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Jamalpur")){
            
            totalcost = (tax *( Milesk20+fclass)*2) /100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (Milesk20+fclass)*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk20+fclass+totalcost) *2)-28.05);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("FirstClass");
             tricketT1.setText("RETURN");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
         ///one way///////
        if ((FirstC .isSelected()) && ( Single.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Haluaghat")){
            
            totalcost = (tax * (Milesk30+fclass))/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", Milesk30+fclass);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f",fclass+ Milesk30+totalcost);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("Firstclass");
             tricketT1.setText("NOE way");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
            
            
        }
        ///one 2 way ///////
        else if ((FirstC .isSelected()) && ( Return.isSelected()) && (Ayes.isSelected()) && Choose.getSelectedItem().equals("Haluaghat")){
            
            totalcost = (tax * (fclass+Milesk30)*2)/100;
            String sTax = String.format("total % .2f",totalcost);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (fclass+Milesk30)*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk30+fclass+totalcost)*2);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("FirstClass");
             tricketT1.setText("RETURN");
             Adtext.setText("ONE");
             Chtext.setText("Nill");
        }
        }
        /// 3 way/////
         else if ((FirstC.isSelected()) && ( Single.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Haluaghat")){
            
            totalcost = (tax * (fclass+Milesk30))/100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (fclass+Milesk30));
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", (Milesk30+fclass+totalcost)-5.19);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("FirstClass");
             tricketT1.setText("ONE WAY");
             Adtext.setText("Nill");
             Chtext.setText("one");
            
        }
}
         ///// 4 way/////
        else if ((FirstC .isSelected()) && ( Return.isSelected()) && (Cyes.isSelected()) && Choose.getSelectedItem().equals("Haluaghat")){
            
            totalcost = (tax *( Milesk30+fclass)*2) /100;
            String sTax = String.format("total % .2f",totalcost-18);
            Taxtext.setText(sTax);
            String Stotal = String .format("total %.2f", (Milesk30+fclass)*2);
            Subtext.setText(Stotal);
            String Total = String.format("total %.2f", ((Milesk30+fclass+totalcost) *2)-28.05);
            Totaltext.setText(Total);
            Pricetext.setText(Total);
            Cltext.setText("FirstClass");
             tricketT1.setText("RETURN");
             Adtext.setText("Nill");
             Chtext.setText("one");
    }                                       
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project().setVisible(true);
            }
        });


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adtext;
    private javax.swing.JLabel Adult;
    private javax.swing.JLabel Adult1;
    private javax.swing.JRadioButton Ayes;
    private javax.swing.JLabel Chaild1;
    private javax.swing.JLabel Child;
    private javax.swing.JComboBox<String> Choose;
    private javax.swing.JTextField Chtext;
    private javax.swing.JLabel Class;
    private javax.swing.JLabel Classte;
    private javax.swing.JTextField Cltext;
    private javax.swing.JRadioButton Cyes;
    private javax.swing.JLabel Date;
    private javax.swing.JTextField Datetext;
    private javax.swing.JLabel Destination;
    private javax.swing.JRadioButton Economy;
    private javax.swing.JButton Exit;
    private javax.swing.JRadioButton FirstC;
    private javax.swing.JLabel From;
    private javax.swing.JTextField Fromtext;
    private javax.swing.JLabel Price;
    private javax.swing.JTextField Pricetext;
    private javax.swing.JButton Resent;
    private javax.swing.JRadioButton Return;
    private javax.swing.JLabel Rount;
    private javax.swing.JTextField Rounttext;
    private javax.swing.JRadioButton Single;
    private javax.swing.JRadioButton Standrad;
    private javax.swing.JTextField Subtext;
    private javax.swing.JLabel SunTotal;
    private javax.swing.JTextField TNoText;
    private javax.swing.JLabel Tax;
    private javax.swing.JTextField Taxtext;
    private javax.swing.JLabel TicketNo;
    private javax.swing.JLabel Tickettype1;
    private javax.swing.JLabel Time;
    private javax.swing.JTextField Timetext;
    private javax.swing.JLabel To;
    private javax.swing.JLabel Total;
    private javax.swing.JButton Totalbuttn;
    private javax.swing.JTextField Totaltext;
    private javax.swing.JTextField Totext;
    private javax.swing.JLabel TrainTicket;
    private javax.swing.JLabel Trickettype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField tricketT1;
    // End of variables declaration//GEN-END:variables
}
}